# Staging environment values
global:
  imageRegistry: ghcr.io/bromso/kitchensink-react/
  environment: staging
  domain: staging.kitchensink-react.com

namespace:
  name: kitchensink-react-staging

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: staging.kitchensink-react.com
      paths:
        - path: /
          pathType: Prefix
          service: www
          port: 3000
        - path: /app
          pathType: Prefix
          service: app
          port: 3001
        - path: /docs
          pathType: Prefix
          service: docs
          port: 3003
        - path: /legal
          pathType: Prefix
          service: legal
          port: 3002
  tls:
    - secretName: kitchensink-react-staging-tls
      hosts:
        - staging.kitchensink-react.com

app:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4

www:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6

docs:
  replicaCount: 1

legal:
  replicaCount: 1
